server:
  port : 8084

spring:
  application:
    name : security
  datasource:
    url: jdbc:mysql://localhost:3306/exam
    username : root
    password : 1234
    driver-class-name : com.mysql.jdbc.Driver